baseURL = 'https://todwestcott.com/'
languageCode = 'en-us'
title = 'Tod Westcott'

[menu]
[[menu.main]]
name = "Tod Westcott"
url = "/"
weight = 1

[[menu.main]]
name = "About Site"
url = "/about-site/"
weight = 2

[[menu.main]]
name = "About Me"
url = "/about-me/"
weight = 3

[[menu.main]]
name = "Contact"
url = "/contact/"
weight = 3

[params]
images = [
    { url = "images/scaled-6x7/post-1.jpg", alt = "post-5 images", description = "The Coming Harvest", link = "/post-5"},
    { url = "images/scaled-6x7/post-2.jpg", alt = "post-1 images", description = "Does God Send Anyone to Hell?", link = "/post-3"},
    { url = "images/scaled-6x7/post-3.jpg", alt = "post-2 images", description = "Is Perfection Required for Heaven?", link = "/post-2"},
    { url = "images/scaled-6x7/post-4.jpg", alt = "post-e images", description = "What is Missing in the Western Gospel?", link = "/post-1"}
]